### ISSUE TITLE
StakingSudo::ProcessQueue is still necessary, despite deprecation warnings.

### ISSUE THREAD

**Issue by AmitPr** [CosmWasm/cw-multi-test#127] opened 2024-01-31 22:08 UTC
If I do not call

```rs
app.sudo(SudoMsg::Staking(StakingSudo::ProcessQueue {})).unwrap();
```
After updating the block time, when I have an unbonding that should be disbursed:
```rs
app.update_block(|block| {
    block.time = block.time.plus_seconds(60);
});
```
Then the unstaked tokens do not get distributed to the address that unbonded them.

This is despite the deprecation message:
```
use of deprecated variant `cw_multi_test::StakingSudo::ProcessQueue`: This is not needed anymore. Just call `update_block`
```

**Comment by maurolacy** [comment] 2024-02-01 20:44
You should update the block height as well, isn't? Perhaps updating the block's time alone should be removed from the API btw.

**Comment by DariuszDepta** [comment] 2024-02-05 10:51
Hi @AmitPr, where can I take a look at your test case? I would like to reproduce this locally.

**Comment by DariuszDepta** [comment] 2024-02-09 13:23
Hi @maurolacy, could you (when you have time, of course) just list (in bullet points) how to simulate this situation in test?

**Comment by maurolacy** [comment] 2024-02-09 17:52
Point is, that perhaps (haven't checked) OP was modifying only the block time, not block height. And that shouldn't be a valid operation, as it's not possible to do that in a real blockchain setting.

In fact the only meanigful operation would be something like `advance_block`, in which both the height and time are modified.

**Comment by maurolacy** [comment] 2024-02-11 16:02
After seeing the code it seems there's a bug there, as `update_block` by default increases both the block's time and height.

**Comment by maurolacy** [comment] 2024-02-11 16:05
Not sure how to improve on this, but letting people play with the block freely seems to confusing.

**Comment by DariuszDepta** [comment] 2024-03-07 08:48
I am closing this issue, but filed a dedicated task to cover this case: #136

**Comment by AmitPr** [comment] 2024-05-04 23:25
Hi @DariuszDepta, @maurolacy,

Sorry for the very late update. Have just finally gotten around to figuring out why the behavior differs. Here's my testcase:

```rust
    let (mut app, a) = setup_env();
    do_stake(&mut app, 200u128).unwrap();
    app.update_block(|block| {
        block.height += 1;
        block.time = block.time.plus_seconds(86400);
    });
    app.sudo(SudoMsg::Staking(StakingSudo::ProcessQueue {}))
         .unwrap();
    do_unstake(&mut app, 100u128).unwrap();
    app.update_block(|block| {
        block.height += 1;
        block.time = block.time.plus_seconds(60);
    });
    app.sudo(SudoMsg::Staking(StakingSudo::ProcessQueue {}))
        .unwrap();
```

As you can see, I'm updating the block time, and then triggering the staking module operations.

In the `update_block` function, you can see the following order of operations:

```rust
    // this let's use use "next block" steps that add eg. one height and 5 seconds
    pub fn update_block<F: Fn(&mut BlockInfo)>(&mut self, action: F) {
        self.router
            .staking
            .process_queue(&self.api, &mut self.storage, &self.router, &self.block)
            .unwrap();
        action(&mut self.block);
    }
```

Meaning that the staking module's operations are triggered _before_ the block is updated. Not sure whether there's a reason for this order of operations, but this seems pretty unintuitive -- Wouldn't we expect that the staking operations happen after the block is updated, simulating logic running in the `BeginBlocker`?

**Comment by maurolacy** [comment] 2024-05-09 07:47
Yes, changing the order looks like a good idea. It'll be compatible with the previous behaviour as well.

**Closed** 2024-06-11 13:09 UTC
